---
AllCops:
  TargetRubyVersion: 2.4

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Exclude:
    - "**/test/*_test.rb"
Metrics/MethodLength:
  Exclude:
    - "**/test/*_test.rb"
